In [6]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler, LabelEncoder

In [7]:
iris=load_iris(as_frame=True)
df=iris.frame
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [8]:
print("Shape of dataset: ", df.shape)

Shape of dataset:  (150, 5)

In [9]:
print("Column Names")
print(df.columns.to_list())

Column Names
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'target']

In [10]:
print("Dataset information")
print(df.info())

Dataset information
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB
None

In [11]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
dtype: int64

In [12]:
print("Total missing vales")
print(df.isnull().sum().sum())

Total missing vales
0

In [13]:
print(df.dtypes)

sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
target                 int64
dtype: object

In [14]:
print("Integer columns: ",df.select_dtypes(include=["int"]).columns.to_list())
print("Float columns: ",df.select_dtypes(include=["float"]).columns.to_list())
print("Character columns:", df.select_dtypes(include=["object"]).columns.tolist())
print("Logical columns:", df.select_dtypes(include=["bool"]).columns.tolist())

Integer columns:  ['target']
Float columns:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Character columns: []
Logical columns: []

In [15]:
df["species"]=df["target"].map(dict(enumerate(iris.target_names)))
df=df.drop(columns=["target"])
df["species"]=df["species"].astype("category")
print(df.dtypes)
display(df.head())

sepal length (cm)     float64
sepal width (cm)      float64
petal length (cm)     float64
petal width (cm)      float64
species              category
dtype: object

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [16]:
print("Duplicate values: ",df.duplicated().sum())

Duplicate values:  1

In [17]:
df.drop_duplicates()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [18]:
print("after removing duplicate values: ",df.shape)

after removing duplicate values:  (150, 5)

In [19]:
df.columns=(
        df.columns
        .str.strip()
        .str.lower()
        .str.replace(" ","_")
        .str.replace(r"[^\w]","",regex=True)
)
print(df.columns.tolist())
print(df.head())

['sepal_length_cm', 'sepal_width_cm', 'petal_length_cm', 'petal_width_cm', 'species']
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

In [20]:
encoder=LabelEncoder()
df["species_encoded"]=encoder.fit_transform(df["species"])
print("species encoding:")
print(dict(zip(encoder.classes_,encoder.transform(encoder.classes_))))
display(df[["species","species_encoded"]].head(10))

species encoding:
{'setosa': np.int64(0), 'versicolor': np.int64(1), 'virginica': np.int64(2)}

  species  species_encoded
0  setosa                0
1  setosa                0
2  setosa                0
3  setosa                0
4  setosa                0
5  setosa                0
6  setosa                0
7  setosa                0
8  setosa                0
9  setosa                0

In [21]:
features=[
    "sepal_length_cm",
    "sepal_width_cm",
    "petal_length_cm",
    "petal_width_cm"
]
scaler=MinMaxScaler()
df_normalized=df.copy()
df_normalized[features]=scaler.fit_transform(df_normalized[features])
display(df_normalized.head())

,sepal_length_cm,sepal_width_cm,petal_length_cm,petal_width_cm,species,species_encoded
0,0.222222,0.625000,0.067797,0.041667,setosa,0
1,0.166667,0.416667,0.067797,0.041667,setosa,0
2,0.111111,0.500000,0.050847,0.041667,setosa,0
3,0.083333,0.458333,0.084746,0.041667,setosa,0
4,0.194444,0.666667,0.067797,0.041667,setosa,0

In [23]:
print("Minimum values:")
print(df_normalized[features].min())

Minimum values:
sepal_length_cm    0.0
sepal_width_cm     0.0
petal_length_cm    0.0
petal_width_cm     0.0
dtype: float64

In [24]:
print("Maximum values:")
print(df_normalized[features].max())

Maximum values:
sepal_length_cm    1.0
sepal_width_cm     1.0
petal_length_cm    1.0
petal_width_cm     1.0
dtype: float64

In [25]:
print("Final normalized shape:", df_normalized.shape)
print()

Final normalized shape: (150, 6)